server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: PAYMENT-SERVICE

logging:
  file: C:/Users/jayshah4/OneDrive - Publicis Groupe/Desktop/logs/microservice.log